

#server:
#  port: 8888
## our own configuration for the file storage
#file:
#  storage-dir: "filestorage/images/"
#  client-dir: "/images/**"
#
#spring :
#  servlet:
#    multipart:
#      max-file-size: 5MB
#      max-request-size: 5MB
#  datasource:
#    username: postgres
#    password: 1234567890
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop # or update
#    generate-ddl: true
#springdoc:
#  swagger-ui:
#    path: /
#


