server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/E-learning_Rest_API

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  springdoc:
    swagger-ui:
      path: /